export type ProductCategory =
  | "Hogar y Cocina"
  | "Herramientas y Electricidad"
  | "Iluminación y LED"
  | "Audio Video y Parlantes"
  | "Electrónica y Computación"
  | "Juegos Juguetes y Librería"
  | "Gadgets"
  | "Bazar y Camping"
  | "Indumentaria y Textiles"
  | "Cuidado Personal y Cosmética"
  | "Cables y Conectores"
  | "Seguridad y Cámaras"
  | "Cargadores y Fuentes"
  | "Accesorios para Celulares"
  | "Accesorios Auto Moto y Bici"
  | "Liquidación"
  | "Próximo a Ingresar";

const CATEGORIES: Record<ProductCategory, string[]> = {
  "Hogar y Cocina": [
    "cocina",
    "horno",
    "refrigerador",
    "nevera",
    "microondas",
    "licuadora",
    "batidora",
    "cafetera",
    "hervidor",
    "tetera",
    "olla",
    "sartén",
    "plato",
    "vaso",
    "cuchara",
    "tenedor",
    "cuchillo",
    "tabla",
    "colador",
    "escurridor",
    "trapo",
    "esponja",
    "detergente",
    "limpiar",
    "basura",
    "tacho",
    "organizador",
    "caja",
    "recipiente",
    "tupperware",
    "mantel",
    "cortina",
    "persiana",
    "cortinero",
    "espejo",
    "lámpara cocina",
    "campana",
    "extractora",
    "anafe",
    "pistola riego",
    "riego",
    "jardín",
    "jardinería",
    "plantas",
    "reloj",
    "reloj digital",
    "despertador",
    "alarma",
    "pava",
    "tetera",
    "molde silicona",
    "freidora aire",
    "organizador baño",
    "organizador",
    "encendedor",
    "encendedor recargable",
    "humidificador",
    "balanza",
    "balanza de cocina",
    "balanza digital",
    "balanza baño",
    "balanza electrónica",
    "bascula",
    "bascula cocina",
    "tender",
    "tendedero",
    "tendedero ropa",
    "tender ropa",
    "secadora ropa",
    "lavarropa",
    "lavadora",
    "lavadora portátil",
    "lavarropa portátil",
    "mini lavarropa",
    "lavadora mini",
    "aspiradora",
    "aspiradora portátil",
    "aspiradora eléctrica",
    "máquina de coser",
    "costurera",
    "jarra",
    "jarra de vidrio",
    "jarra vidrio",
    "jarra cerámica",
    "jarra agua",
  ],
  "Herramientas y Electricidad": [
    "herramienta",
    "destornillador",
    "martillo",
    "sierra",
    "taladro",
    "amoladora",
    "soldadora",
    "pinza",
    "llave",
    "tornillo",
    "clavo",
    "tuerca",
    "broca",
    "mecha",
    "cable",
    "extensión",
    "enchufe",
    "tomacorriente",
    "interruptor",
    "disyuntor",
    "fusible",
    "electricidad",
    "voltaje",
    "corriente",
    "transformador",
    "generador",
    "bateria",
    "cargador",
    "inversor",
    "estabilizador",
  ],
  "Iluminación y LED": [
    "luz",
    "lámpara",
    "foco",
    "bombilla",
    "led",
    "linterna",
    "reflector",
    "spot",
    "tira led",
    "candela",
    "vela",
    "iluminación",
    "luminaria",
    "aplique",
    "downlight",
    "panel led",
    "tubo",
    "fluorescente",
    "halógeno",
    "ahorro",
    "energía",
    "watts",
    "lúmenes",
    "control remoto luz",
    "dimmer",
    "ventilador led",
    "ventilador de techo",
    "cartel",
    "cartel abierto",
    "cartel neón",
    "cartel led",
    "neón",
    "antorcha",
    "antorcha solar",
    "antorcha led",
    "antorcha estaca",
  ],
  "Audio Video y Parlantes": [
    "audio",
    "video",
    "parlante",
    "speaker",
    "micrófono",
    "micrófono inalámbrico",
    "karaoke",
    "audífono",
    "auricular",
    "auriculares",
    "auriculares inalámbricos",
    "auriculares bluetooth",
    "headphones",
    "headset",
    "in-ear",
    "over-ear",
    "vincha",
    "vincha bluetooth",
    "vincha bt",
    "diadema",
    "diadema bluetooth",
    "equipo de música",
    "amplificador",
    "mezclador",
    "dvd",
    "blu ray",
    "proyector",
    "televisor",
    "tv",
    "televisión",
    "receptor",
    "decodificador",
    "cámara",
    "videocámara",
    "grabadora",
    "reproductor",
    "tocadiscos",
    "estéreo",
    "radio",
    "fm",
    "am",
    "tuner",
    "crossover",
    "ecualizador",
    "barra sonido",
    "soundbar",
    "woofer",
    "subwoofer",
    "tweeter",
    "bt",
    "bluetooth",
    "inalámbrico",
    "wireless",
    "tv box",
    "box streaming",
    "dispositivo streaming",
    "android tv",
    "parlante",
    "barra parlante",
    "auto parlante",
    "rgb",
    "parlante rgb",
    "soporte tv",
    "soporte televisor",
    "soporte para tv",
    "soporte 14-55",
    "soporte 14-42",
    "soporte 26-63",
  ],
  "Electrónica y Computación": [
    "computadora",
    "computador",
    "laptop",
    "notebook",
    "pc",
    "desktop",
    "monitor",
    "teclado",
    "mouse",
    "ratón",
    "mousepad",
    "webcam",
    "impresora",
    "escáner",
    "multifunción",
    "router",
    "módem",
    "switch",
    "hub",
    "adaptador",
    "docking",
    "dock",
    "disco duro",
    "ssd",
    "pendrive",
    "memoria",
    "ram",
    "procesador",
    "motherboard",
    "fuente poder",
    "fan",
    "ventilador",
    "disipador",
    "pasta térmica",
    "cable usb",
    "cable ethernet",
    "cable hdmi",
    "cable vga",
    "cable de poder",
    "software",
    "licencia",
    "antivirus",
    "windows",
    "linux",
    "mac",
    "antena",
    "antena wifi",
    "wifi",
    "joystick",
    "gamepad",
    "mando",
    "control juego",
    "periférico",
    "ps4",
    "xbox",
    "antena",
    "antena wifi",
  ],
  "Juegos Juguetes y Librería": [
    "juego mesa",
    "juego infantil",
    "juguete",
    "juguete infantil",
    "peluche",
    "muñeca",
    "acción figure",
    "figura",
    "lego",
    "construcción",
    "bloques",
    "puzzle",
    "rompecabezas",
    "videojuego",
    "consola",
    "nintendo",
    "playstation",
    "xbox",
    "sega",
    "carrito juguete",
    "auto juguete",
    "control remoto juguete",
    "rc",
    "avión juguete",
    "patineta juguete",
    "skate juguete",
    "patín juguete",
    "monopatin juguete",
    "balero",
    "pelota",
    "pelota juguete",
    "balón",
    "futbol",
    "voleibol",
    "basket",
    "tennis",
    "raqueta",
    "tenis",
    "boliche",
    "mesa de juego",
    "tablero",
    "cartas",
    "dados",
    "dominó",
    "ajedrez",
    "damas",
    "marcadores",
    "marcador",
    "papelería",
    "útiles",
    "útiles escolares",
    "escuela",
    "lápiz",
    "lápices",
    "bolígrafo",
    "bolígrafos",
    "pluma",
    "plumas",
    "cuaderno",
    "cuadernos",
    "libreta",
    "papel",
    "cartulina",
    "goma",
    "borrador",
    "corrector",
    "regla",
    "compás",
    "transportador",
    "resaltador",
    "highlighter",
    "tinta",
    "pintura",
    "acuarela",
    "calculadora",
    "calculadora científica",
    "calculadora digital",
    "calculadora de bolsillo",
    "óleo",
    "pastel",
    "libro",
    "libros",
    "novela",
    "cuento",
    "poesía",
    "ensayo",
    "manual",
    "guía",
    "diccionario",
    "enciclopedia",
    "revista",
    "periódico",
    "cómic",
    "historieta",
    "manga",
    "novela gráfica",
    "infantil",
    "niños",
    "cuento infantil",
    "fábula",
    "educativo",
    "académico",
    "técnico",
    "ficción",
    "ciencia ficción",
    "fantasía",
    "misterio",
    "terror",
    "romance",
    "suspenso",
    "thriller",
    "biografía",
    "historia",
    "autoayuda",
    "desarrollo personal",
    "motivacional",
    "religión",
    "filosofía",
    "arte",
    "arquitectura",
    "diseño",
    "moda",
    "gastronomía",
    "viajes",
    "deportes",
    "salud",
    "bienestar",
    "meditación",
    "yoga",
    "fitness",
    "nutrición",
    "recetas",
    "cocina",
    "pizarra",
    "pizarrón",
  ],
  "Gadgets": [
    "gadget",
    "smartphone",
    "celular",
    "móvil",
    "teléfono",
    "iphone",
    "samsung",
    "xiaomi",
    "tablet",
    "ipad",
    "pulsera inteligente",
    "smartwatch",
    "reloj inteligente",
    "banda fitness",
    "smart home",
    "hogar inteligente",
    "sensor",
    "alarma",
    "cámara de seguridad",
    "timbre video",
    "cerradura inteligente",
    "termostato",
    "detector humo",
    "detector movimiento",
    "control inteligente",
    "bombilla inteligente",
    "enchufe inteligente",
    "aroma difusor",
    "humidificador",
    "ventilador inteligente",
    "climatizador",
    "air purifier",
    "purificador aire",
    "deshumidificador",
    "mini proyector",
    "drone",
    "scooter",
    "monociclo",
    "hoverboard",
    "selfie stick",
    "trípode",
    "gimbal",
    "estabilizador",
    "power bank",
    "batería externa",
    "cargador inalámbrico",
    "wireless",
    "bluetooth",
    "wi-fi",
  ],
  "Bazar y Camping": [
    "camping",
    "carpa",
    "tienda campaña",
    "saco dormir",
    "bolsa dormir",
    "colchoneta",
    "almohada",
    "mochila",
    "morral",
    "bolsa",
    "malet",
    "maleta",
    "bazar",
    "hogar",
    "viaje",
    "turismo",
    "excursión",
    "senderismo",
    "escalada",
    "montaña",
    "playa",
    "piscina",
    "nautica",
    "kayak",
    "tabla paddle",
    "snorkel",
    "buceo",
    "caña pescar",
    "anzuelo",
    "red",
    "brújula",
    "mapa",
    "gps",
    "linterna",
    "frontal",
    "mochila dorsal",
    "cantimplora",
    "botella",
    "termo",
    "cooler",
    "heladera",
    "picnic",
    "mantel picnic",
    "silla camping",
    "hamaca",
    "cuerda",
    "cinta",
    "multiherramienta",
    "navaja",
    "brújula",
    "silbato",
    "linterna",
    "linterna camping",
    "linterna recargable",
    "linterna solar",
    "linterna multifunción",
    "sillón inflable",
    "inflador",
    "inflador multiuso",
    "frapera",
    "hielera",
    "cooler",
    "botella",
    "botella termo",
    "botella térmica",
    "botella termica",
    "termo",
  ],
  "Indumentaria y Textiles": [
    "ropa",
    "prenda",
    "camiseta",
    "remera",
    "buzo",
    "sudadera",
    "campera",
    "abrigo",
    "chamarra",
    "chaqueta",
    "pantalón",
    "bermuda",
    "short",
    "falda",
    "vestido",
    "pollera",
    "blusa",
    "camisa",
    "pijama",
    "bata",
    "medias",
    "calcetines",
    "zapato",
    "zapatilla",
    "bota",
    "chancla",
    "sandalia",
    "cinturón",
    "corbata",
    "bufanda",
    "gorro",
    "gorro con luz",
    "gorro led",
    "sombrero",
    "gafas",
    "lentes",
    "anteojos",
    "bolso",
    "cartera",
    "mochila",
    "maletin",
    "cintura",
    "joyas",
    "pulsera",
    "collar",
    "anillo",
    "aros",
    "aro",
    "reloj",
    "pulsera",
    "guante",
    "mitón",
    "bufanda",
    "pashmina",
    "tela",
    "tejido",
    "algodón",
    "poliéster",
    "lana",
    "seda",
    "lino",
  ],
  "Cuidado Personal y Cosmética": [
    "jabón",
    "champú",
    "shampoo",
    "acondicionador",
    "gel",
    "crema",
    "loción",
    "perfume",
    "colonia",
    "desodorante",
    "espray",
    "talco",
    "polvos",
    "higiene",
    "cepillo dientes",
    "pasta dientes",
    "enjuague",
    "hilo dental",
    "cepillo cabello",
    "peine",
    "secador",
    "plancha",
    "rizador",
    "máquina afeitar",
    "rasuradora",
    "espuma afeitar",
    "aftershave",
    "balm",
    "aceite",
    "serum",
    "mascarilla",
    "exfoliante",
    "maquillaje",
    "labial",
    "lápiz labios",
    "sombra",
    "rimel",
    "delineador",
    "base",
    "polvo compacto",
    "rubor",
    "blush",
    "removedor maquillaje",
    "toallitas",
    "papel higiénico",
    "pañuelos",
    "toalla",
    "servilleta",
    "algodón",
    "gasa",
    "vendaje",
    "apósito",
    "esparadrapo",
    "termómetro",
    "tensiometro",
    "glucómetro",
    "vitamina",
    "suplemento",
    "pastilla",
    "cápsula",
    "jarabe",
    "pomada",
    "ungüento",
    "cejas",
    "perfilador",
    "perfilador cejas",
    "sobrancelera",
    "secadora brochas",
    "secadora",
    "brochas maquillaje",
    "brocha",
    "belleza",
    "cosmética",
    "estética",
    "corta pelo",
    "cortapelo",
    "cortadora pelo",
    "máquina cortar pelo",
    "rasuradora",
    "cortador",
    "clipper",
    "trimmer",
    "depiladora",
    "depiladora recargable",
    "depiladora eléctrica",
    "cepillo secador",
    "secador cepillo",
    "cepillo moldeador",
    "moldeador",
    "masajeador",
    "masaje",
    "vibrador",
    "electroestimulador",
  ],
  "Cables y Conectores": [
    "cable",
    "cable auxiliar",
    "cable rca",
    "cable tipo c",
    "cable hdmi",
    "cable vga",
    "cable usb",
    "cable ethernet",
    "conector",
    "conector usb",
    "adaptador cable",
    "adaptador usb",
    "usb-c",
    "tipo-c",
    "hdmi",
    "vga",
    "dvi",
    "ethernet",
    "rj45",
    "jack",
    "plug",
    "enchufe",
    "tomacorriente",
    "extensión",
    "regleta",
    "multitoma",
    "cable de poder",
    "cable de alimentación",
    "prolongador",
    "latiguillos",
    "cable coaxial",
    "cable óptico",
    "toslink",
    "mini jack",
    "aux",
    "3.5mm",
    "6.5mm",
    "xlr",
    "dmx",
    "displayport",
    "thunderbolt",
    "lightning",
    "micro usb",
    "mini usb",
    "serial",
    "paralelo",
    "firewire",
    "ide",
    "sata",
    "molex",
    "conector питания",
  ],
  "Seguridad y Cámaras": [
    "cámara seguridad",
    "cámara vigilancia",
    "cámara ip",
    "cámara wifi",
    "cámara 360",
    "cámara térmica",
    "dvr",
    "nvr",
    "grabador",
    "timbre video",
    "video portero",
    "intercomunicador",
    "alarma",
    "sensor",
    "sensor movimiento",
    "sensor humo",
    "detector humo",
    "detector monóxido",
    "cerradura inteligente",
    "cerradura digital",
    "cerradura biométrica",
    "candado",
    "candado inteligente",
    "caja fuerte",
    "guardaespaldas",
    "protección",
    "vigilancia",
    "monitoreo",
    "grabación",
    "enfoque",
    "zoom",
    "visión nocturna",
    "infrarrojo",
    "resolución",
    "megapixel",
    "pixel",
    "lente",
    "objetivo",
  ],
  "Cargadores y Fuentes": [
    "cargador",
    "cargador rápido",
    "cargador inalámbrico",
    "cargador wireless",
    "cargador universal",
    "cargador de pared",
    "cargador de auto",
    "cargador de celular",
    "cargador de laptop",
    "cargador de notebook",
    "cargador de tablet",
    "cargador de baterías",
    "cargador usb",
    "cargador pd",
    "cargador qc",
    "fuente poder",
    "fuente alimentación",
    "fuente psu",
    "transformador voltaje",
    "convertidor voltaje",
    "inversor voltaje",
    "regulador voltaje",
    "estabilizador voltaje",
    "power bank",
    "powerbank",
    "batería externa",
    "batería portátil",
    "acumulador",
  ],
  "Accesorios para Celulares": [
    "funda celular",
    "funda smartphone",
    "funda telefónica",
    "estuche",
    "protector pantalla",
    "vidrio templado",
    "cristal protector",
    "protector celular",
    "mica",
    "screen protector",
    "tempered glass",
    "batería celular",
    "batería smartphone",
    "cargador celular",
    "cargador telefónico",
    "cable celular",
    "cable usb",
    "soporte celular",
    "soporte móvil",
    "soporte sopapa",
    "soporte pinza",
    "soporte rejilla",
    "soporte auto celular",
    "holder",
    "soporte escritorio",
    "soporte teléfono",
    "anillo soporte",
    "ring",
    "pop socket",
    "pop it",
    "popsocket",
    "correa celular",
    "lanyard",
    "cadena celular",
    "screen cleaner",
    "limpiador pantalla",
    "paño",
    "teclado bluetooth",
    "mouse bluetooth",
    "ventilador celular",
    "cooler",
    "radiador",
    "tripode",
    "trípode celular",
    "lente macro",
    "lente gran angular",
    "lente zoom",
    "lente 3d",
    "selfie stick",
    "tripode",
    "monopod",
    "gimbal",
    "estabilizador",
    "doble sopapa",
    "ventosa",
  ],
  "Accesorios Auto Moto y Bici": [
    "auto accesorio",
    "moto accesorio",
    "bici accesorio",
    "bicicleta accesorio",
    "motocicleta accesorio",
    "motoneta",
    "scooter",
    "rueda bici",
    "rueda moto",
    "llanta",
    "neumático",
    "cámara aire",
    "cubierta bicicleta",
    "espejo moto",
    "espejo retrovisor",
    "retrovisor",
    "luz moto",
    "luz bicicleta",
    "luz frontal bici",
    "luz trasera bici",
    "linterna bici",
    "casco moto",
    "casco bici",
    "casco motociclista",
    "guantes moto",
    "guantes bici",
    "protección moto",
    "protección bici",
    "chaleco moto",
    "mochila bici",
    "porta bicicleta",
    "portabicicletas",
    "candado bici",
    "candado moto",
    "linga bici",
    "linga moto",
    "cadena bici",
    "cadena moto",
    "cable bici",
    "soporte teléfono moto",
    "soporte gps moto",
    "soporte celular auto",
    "organizador auto",
    "aspiradora auto",
    "aspiradora portátil auto",
    "aspiradora inalámbrica auto",
    "bandeja",
    "caja almacenamiento",
    "caja herramientas",
    "kit herramientas",
    "inflador",
    "bomba aire",
    "parche",
    "pegamento",
    "aceite",
    "lubricante",
    "desengrasante",
    "limpiador",
    "pulidor",
    "cera",
    "sellador",
    "protector",
  ],
  "Liquidación": [
    "liquidación",
    "oferta",
    "promoción",
    "descuento",
    "rebaja",
    "sale",
    "clearance",
    "stock bajo",
    "últimas unidades",
    "agotado",
    "fin de stock",
    "liquidado",
    "última oportunidad",
    "precio especial",
    "precio reducido",
    "precio único",
    "outlet",
    "remate",
    "quemazón",
    "cierre",
    "saldo",
    "excedente",
    "sobrante",
  ],
  "Próximo a Ingresar": [
    "próximo",
    "próxima llegada",
    "próximo ingreso",
    "por llegar",
    "en camino",
    "preventa",
    "pre-order",
    "preorden",
    "disponible pronto",
    "soon",
    "coming soon",
    "proximamente",
    "próximamente",
    "en breve",
    "en stock pronto",
    "nuevo ingreso",
    "nuevo modelo",
    "nueva colección",
    "edición nueva",
    "lanzamiento",
    "release",
    "debut",
    "estreno",
  ],
};

export interface CategorizationResult {
  primary: ProductCategory;
  alternatives: ProductCategory[];
  confidence: number; // 0-1, qué tan seguro está
  needsConfirmation: boolean; // true si hay dudas
}

export function categorizeProduct(productName: string, productDescription?: string): CategorizationResult {
  const text = `${productName} ${productDescription || ""}`.toLowerCase();
  const words = text.split(/\s+/);

  const scores: Record<ProductCategory, number> = {} as any;

  // Inicializar scores
  (Object.keys(CATEGORIES) as ProductCategory[]).forEach((category) => {
    scores[category] = 0;
  });

  // Calcular score para cada categoría
  (Object.entries(CATEGORIES) as [ProductCategory, string[]][]).forEach(([category, keywords]) => {
    keywords.forEach((keyword) => {
      words.forEach((word) => {
        // Match exacto
        if (word === keyword) {
          scores[category] += 3;
        }
        // Match parcial (word contiene keyword)
        else if (word.includes(keyword)) {
          scores[category] += 1.5;
        }
        // Match parcial (keyword contiene word)
        else if (keyword.includes(word) && word.length > 3) {
          scores[category] += 1;
        }
      });
    });
  });

  // Ordenar por score
  const sorted = (Object.entries(scores) as [ProductCategory, number][]).sort(
    ([, scoreA], [, scoreB]) => scoreB - scoreA
  );

  const primary = sorted[0]?.[0] || "Gadgets";
  const primaryScore = sorted[0]?.[1] || 0;
  const secondaryScore = sorted[1]?.[1] || 0;

  // Calcular confianza (0-1)
  const maxPossibleScore = Math.max(...Object.values(scores));
  const confidence = maxPossibleScore > 0 ? primaryScore / (maxPossibleScore * 1.5) : 0;

  // Si hay una diferencia pequeña entre la categoría 1 y 2, pedir confirmación
  const scoreDifference = primaryScore - secondaryScore;
  const needsConfirmation = confidence < 0.6 || scoreDifference < 2;

  // Alternativas: categorías con score > 30% del score máximo
  const alternatives = sorted
    .slice(1, 4)
    .filter(([, score]) => score > primaryScore * 0.5)
    .map(([category]) => category);

  return {
    primary,
    alternatives: needsConfirmation ? alternatives : [],
    confidence: Math.min(1, Math.max(0, confidence)),
    needsConfirmation,
  };
}

export const CATEGORY_LIST: ProductCategory[] = Object.keys(CATEGORIES) as ProductCategory[];
